### ISSUE TITLE
[Empty] 图标默认尺寸以及按钮样式问题

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#117]
### tdesign-flutter 版本

最新版

### 重现步骤

1、图标的尺寸小于设计稿，请对照设计稿调整下
2、按钮样式有误，请对照设计稿调整下
<img width="479" alt="image" src="https://user-images.githubusercontent.com/94840745/234588564-6454c097-e786-4d78-9216-09b56de468e5.png">

**Comment by Luozf12345** [comment]
已修改：
1.调整icon尺寸
2.按钮文字粗细已在Button中统一修改
