### ISSUE TITLE
[官网走查] 官网示例问题统计

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#136]
### tdesign-flutter 版本

最新版

### 重现链接

http://ty.tdesign.woa.com/flutter/getting-started

### 重现步骤

1、Link 文字与图标错位：http://ty.tdesign.woa.com/flutter/components/link
<img width="348" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/61524867-b37f-4003-a08c-18f268d40ded">

2、NavBar 导航栏文字未居中：http://ty.tdesign.woa.com/flutter/components/navbar
<img width="402" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/3722da96-ebe0-4b8d-92bc-ab2c0aa50550">

3、SideBar 带图标侧边栏文字与图标错位：http://ty.tdesign.woa.com/flutter/components/sidebar
<img width="380" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/ffbc3c66-8cbe-4699-a4e5-9c98f3319193">

4、TabBar 页面背景色颜色有误，应为#F3F3F3；另纯文字样式文字偏下：http://ty.tdesign.woa.com/flutter/components/tabbar
<img width="408" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/dbe46099-56fb-478d-88c6-187e7d489c96">

5、Tabs 前几组选项卡网页中点击时会出现全屏蓝色：http://ty.tdesign.woa.com/flutter/components/tabs
<img width="369" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/f12ede71-5811-47a4-9c00-582e197b72cf">

6、Input 部分组件内文字偏下，且有对齐问题：http://ty.tdesign.woa.com/flutter/components/input
<img width="355" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/70e54bb9-8208-4eb5-bb56-410d05405859">

7、Search 激活时预设文案会往下移动：http://ty.tdesign.woa.com/flutter/components/search
<img width="381" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/558f4501-9eea-4a25-b0ce-41a780f385c0">

8、Stepper 输入文字偏下：http://ty.tdesign.woa.com/flutter/components/stepper
<img width="283" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/b10e7327-e469-4ee7-af37-8e93ad4854a2">

9、Switch 带文字开关文字偏下：http://ty.tdesign.woa.com/flutter/components/switch
<img width="353" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/208d7c27-6bfd-4580-9278-47a16f8d89f7">

10、Avatar 文字版本大尺寸中明显偏下：http://ty.tdesign.woa.com/flutter/components/avatar?tab=demo
<img width="304" alt="image" src="https://github.com/TDesignOteam/tdesign-flutter/assets/94840745/1e0b1b11-3c89-4cc3-a46c-1a9c44edd935">

**Comment by Luozf12345** [comment]
1，3，4，7，9已修改
2，6，8，10是web渲染才有的问题，暂不修改，后面统一适配。
5未复现，我这边点击都是正常的
