### ISSUE TITLE
Swiper轮播图组件开发

### ISSUE THREAD

**Issue by consonluo** [TDesignOteam/tdesign-flutter#14]
### 设计稿
<img width="586" alt="6575dc59-ecde-4cb4-97cd-f53eb2ad0582" src="https://user-images.githubusercontent.com/4338278/185059235-35b0e312-38b7-4307-bf61-45e66c2dfcfb.png">

设计稿：
https://www.figma.com/file/jivYXTMTP3jEkeZXWbMh4J/branch/iluL0hMaj7DFJQXxwFSsUa/TDesign-for-mobile?node-id=4221%3A266

需支持滑动轮播、自动轮播、循环播放模式，可通过参数控制播放模式
需实现设计稿体现的三种类型和多种规格
组件需支持flutter web

### 参与贡献

如果你想要认领组件开发，请在本 issue 中评论认领并预估提交 PR 时间，例：

> “我认领这个组件 tdesign-flutter 仓库的实现任务，预计 x 日后提交”
请尽量在预期时间内完成，超期后 PMC 同学可能会联系其他同学接手实现。

详细提交过程请参考：[如何贡献](https://github.com/TDesignOteam/tdesign-flutter)。

欢迎填写[《贡献者加入意向收集》](https://wj.qq.com/s2/9772260/7cbe/)问卷加入 TDesign 贡献者群，参与过程中遇到的各类问题可以得到实时解答和指引。

**Comment by sara010** [comment]
我认领这个组件 tdesign-flutter 仓库的实现任务，预计 10日后（9.2左右）提交
