### ISSUE TITLE
[组件库] 无法安装（Could not find a file named "pubspec.yaml"）

### ISSUE THREAD

**Issue by LcFireRabbit** [TDesignOteam/tdesign-flutter#145]
### tdesign-flutter 版本

v0.1.8

### 重现步骤

1.在Windows系统创建项目
2.在pubspec.yaml中添加TDesign
3.保存文件

### 期望结果

可以正常安装

### 实际结果

![image](https://github.com/TDesignOteam/tdesign-flutter/assets/40254970/1a4ea143-ad57-4ce4-9007-7b10f915bfd1)

### Flutter版本

3.16.0

### 设备与机型信息

Windows10

### 系统版本

Windows10

**Comment by zhouhj1993** [comment]
tdesign_flutter:
    git:
      url: https://github.com/TDesignOteam/tdesign-flutter.git
      path: tdesign-component
![QQ截图20231130092034](https://github.com/TDesignOteam/tdesign-flutter/assets/54570365/b08efe02-fcc1-4cbe-84b5-9f81a2cb1688)

**Comment by LcFireRabbit** [comment]
可以了，多谢
