### ISSUE TITLE
TDesign项目进展

### ISSUE THREAD

**Issue by Luozf12345** [TDesignOteam/tdesign-flutter#68]
# TODO事项：
+ 一期组件开发走查
+ API文档完善

# 进展
Text、Image、Button等一期组件已开发完成，视觉走查中。
一期组件包含：
Text文本
Icon图标
Image图片
容器组件
Button按钮
Divider 分割线
Avatar头像
Badge徽标
Empty空状态
Toast轻提示
Swiper轮播图
Tag标签
DatetimePicker时间选择器
Input输入框
Picker选择器
Search搜索框
NavBar导航栏
Tabs选项卡
Loading加载
PullDownRefresh下拉刷新
Checkbox多选框
Radio单选框
Switch开关
Dialog对话框
Popup弹出层
TabBar标签栏

example项目中提供了完整的演示示例

详见：https://doc.weixin.qq.com/sheet/e3_AHIAdgbdAFw7bziTffPRbKPSbnX6w?scode=AJEAIQdfAAoo6jYZ5QACIACQZIACg&tab=BB08J2

API文档生成工具开发中，预计3.17前完成。

**Comment by Luozf12345** [comment]
API文档生成工具进展：新增静态方法和工厂构造方法API，支持展示组件类注释。

**Comment by Luozf12345** [comment]
已更新API文档，web端示例项目可查看最新API：https://xinyue.qq.com/tdesign_example/#/

**Comment by XuJin186** [comment]
一直都有关注此项目  此项目的设计个人非常喜欢  请问有发布正式版本的计划吗

**Comment by Luozf12345** [comment]
1.Theme兼容官方ThemeExtension使用方式。
2.替换主题颜色为新版，并添加所有颜色展示样例。
3.近期优先处理一起组件走查，走查完成后可发一期正式版本。

**Comment by Luozf12345** [comment]
一期组件走查：完成Tag、TabBar、NavBar等问题修改。其他走查issue都已提issueShoot招募。

**Comment by Luozf12345** [comment]
1.完善走查流程，新建走查表格，并记录走查状态，每周更新。
2.Tag、Dialog已走查通过。Link、Stepper走查后修改中
