### ISSUE TITLE
[主题] flutter扩展主题

### ISSUE THREAD

**Issue by XuJin186** [TDesignOteam/tdesign-flutter#69]
### 这个功能解决了什么问题

现有的主题模式无法和flutter官方契合

### 你建议的方案是什么

使用官方ThemeExtension

**Comment by Luozf12345** [comment]
请问你们对官方Theme的用法是什么样的呢？TDTheme支持传入官方的ThemeData，能否满足你们需求？

**Comment by XuJin186** [comment]
// 配置
ThemeData.light().copyWith(
  extensions: <ThemeExtension<dynamic>>[
    GradientColors.light(), // 将自己定义的ThemeExtension添加到ThemeData的extensions中
  ],
  ...
)

// 使用
final GradientColors gradientColors = Theme.of(context).extension<GradientColors>()!; // 配置过了就大胆用!吧

**Comment by Luozf12345** [comment]
我这边看下，尽量在一期走查结束之前改造完成

**Comment by XuJin186** [comment]
@Luozf12345 请问是否有进展

**Comment by Luozf12345** [comment]
TDTheme已支持ThemeExtension扩展方式，可以看下是否满足你门需求吧
