### ISSUE TITLE
[demo页展示] 关于demo页展示结构的通用问题

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#71]
### tdesign-flutter 版本

最新版

### 重现步骤

1. 一级组件标题应为Headline-small，需加粗
2. 页面内的模块间距，请参考设计稿，以及如下规范
（1）一级模块为大类的内容分类，模块间间距为32px（一级标题前）
（2）二级模块为具体组件的类型，模块间间距为24px（二级标题前）
（3）二级模块内所有元素间距为16px
![image](https://user-images.githubusercontent.com/94840745/224086919-5e6d39b1-22c7-4fa6-8119-89cd7ff9a1f7.png)

**Comment by Luozf12345** [comment]
已调整，请用最新包走查

**Comment by Luozf12345** [comment]
已调整公告示例组件，先关闭，如果走查有问题再reopen
