### ISSUE TITLE
[Image] 设计走查-图片加载样式有误

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#73]
### tdesign-flutter 版本

最新版

### 重现步骤

请对照设计稿显示为加载效果
<img width="412" alt="image" src="https://user-images.githubusercontent.com/94840745/224088778-8267503a-58e7-4eb7-89eb-dddab4405f3e.png">

**Comment by jflin19990707** [comment]
已修改，最新包验证
