### ISSUE TITLE
[Checkbox] 设计走查-头部缺少组件一句话描述文案

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#75]
### tdesign-flutter 版本

最新版

### 重现步骤

缺少描述：用于预设的一组选项中执行多项选择，并呈现选择结果。
<img width="408" alt="image" src="https://user-images.githubusercontent.com/94840745/224091687-e6177309-2575-4977-b436-20ae8ebd2286.png">

**Comment by jflin19990707** [comment]
已修改，最新包验证
