### ISSUE TITLE
[DateTimePicker] 设计走查-标题字号问题&滚动惯性问题

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#76]
### tdesign-flutter 版本

最新版

### 重现步骤

1、标题应为Title-large:18px加粗
<img width="416" alt="image" src="https://user-images.githubusercontent.com/94840745/224092901-061c5767-a9a9-4af2-b639-a28ac6a633eb.png">

2、滚动选项时，能否稍微快一点停下？感觉目前操作的惯性有点大，松手后滚轮仍会滚动较长距离才停止

**Comment by Luozf12345** [comment]
1.标题字号已修改，请用最新包走查
2.滑动惯性是Flutter系统自带，修改工作量较大，暂不处理，后续升级SDK看官方是否提供相应API，再评估处理。

**Comment by pageee1021** [comment]
辛苦确认下标题上面的间距是否为16px，目前实现效果看着比设计稿要小
<img width="741" alt="image" src="https://user-images.githubusercontent.com/94840745/234592294-3a55a4c6-183c-449a-b046-004deab5c34b.png">
