### ISSUE TITLE
[Checkbox&Radio] 默认尺寸&间距&对齐问题

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#79]
### tdesign-flutter 版本

最新版

### 重现步骤

以下为checkbox多选和radio单选的共同相似问题，辛苦一起看下

1、多选及单选目前的默认单行行高均为56px（即上下padding为16px），请以最新设计稿为准
2、demo内分类小标题间距有误，距离上面太近
<img width="552" alt="image" src="https://user-images.githubusercontent.com/94840745/227131609-56b7f250-dd42-457a-9ebe-d38706f53ccc.png">
3、非通栏单选样式中样式有误，高度有误，文字靠上了
<img width="548" alt="image" src="https://user-images.githubusercontent.com/94840745/227131794-992a2335-c622-48e8-a42d-a64f8352ce2a.png">
4、特殊样式中，文字与左侧间距请参照设计稿，应为16px
<img width="514" alt="image" src="https://user-images.githubusercontent.com/94840745/227131992-48a55325-c978-4463-954d-9d4f140083d1.png">

另radio中demo页缺少了组件描述
<img width="506" alt="image" src="https://user-images.githubusercontent.com/94840745/227132164-5a782e99-6545-4dd8-a55e-1aca697dead8.png">

**Comment by pageee1021** [comment]
非通栏多选/单选样式中，信息仍然位置偏移了，辛苦统一调整下
<img width="621" alt="image" src="https://user-images.githubusercontent.com/94840745/234585087-65bf13f5-39f6-4ff1-adde-cfa825155c3b.png">
<img width="612" alt="image" src="https://user-images.githubusercontent.com/94840745/234585322-da4a09a2-5f31-4d09-b833-cd0f5d90864b.png">

**Comment by Luozf12345** [comment]
已修改
