### ISSUE TITLE
[NavBar] 图标尺寸问题&带搜索时交互状态问题

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#82]
### tdesign-flutter 版本

最新版

### 重现步骤

1、第二类navbar的左侧图标偏下，右侧内边距有误
<img width="619" alt="image" src="https://user-images.githubusercontent.com/94840745/227147709-611e581c-127a-42b4-b4d9-57a249a78d69.png">

2、带搜索导航栏中，搜索框激活时不需要出现取消，单纯激活输入框即可
<img width="620" alt="image" src="https://user-images.githubusercontent.com/94840745/227147317-53099e30-0368-4710-9802-56f980809012.png">

**Comment by Luozf12345** [comment]
1.间距和搜索取消按钮已修改，请用最新包走查。
2.图标偏下问题是生产的Icon本身显示偏下，不是NavBar的问题，后面Icon统一排查修改。
3.Icon示例页增加查看边框功能，可以查看生成的Icon是否正常。

**Comment by pageee1021** [comment]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/94840745/234581410-14985800-cda1-4399-b4fd-7cc45d0c4f57.png">
带图片导航栏这里能否参照设计稿，使用TDesign的logo

**Comment by Luozf12345** [comment]
这是因为网络图片没加载出来，已换成本地图片
