### ISSUE TITLE
[TabBar] 分割线问题&demo展示间距问题

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#83]
### tdesign-flutter 版本

最新版

### 重现步骤

1、底部标签栏只有顶部有分割线
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/94840745/227150038-06664e9a-cefd-499f-9cc1-bd38c6d89418.png">

2、demo元素间展示间距过大，且缺少了顶部组件描述文案
<img width="697" alt="image" src="https://user-images.githubusercontent.com/94840745/227150219-84a387f3-f7e0-479e-99d0-d446c7c5abbd.png">

**Comment by Luozf12345** [comment]
已修改，请用最新包走查

**Comment by pageee1021** [comment]
上述问题已确认，补充两个小问题：
1、组件顶部的分割线粗细应为0.5px，目前看着有点粗
2、纯文本标签栏的选中胶囊样式范围过大，选中高度应为32px
<img width="893" alt="image" src="https://user-images.githubusercontent.com/94840745/234583225-6201b362-71d8-4f40-98f3-772b5a6ac705.png">

**Comment by Luozf12345** [comment]
已修改
