### ISSUE TITLE
[Tabs] 选中样式&等距选项卡展示&图标尺寸等问题

### ISSUE THREAD

**Issue by pageee1021** [TDesignOteam/tdesign-flutter#84]
### tdesign-flutter 版本

最新版

### 重现步骤

1、选中条的长度需要参照设计稿，现在偏长了
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/94840745/227153751-e7b87dec-b4b7-4e7b-a4b7-a67f3ad685e8.png">

2、等距选项卡建议展示超出一行可滚动的效果，另外后续（非末端）的选中希望可以保持剧中显示，具体交互可以参照小程序的实现：https://tdesign.tencent.com/miniprogram/components/tabs
<img width="376" alt="image" src="https://user-images.githubusercontent.com/94840745/227154398-4b0bebf6-b8cd-4b32-80c5-c6ac8d7f8b06.png">

3、选项卡需要有底部的分割线
<img width="964" alt="image" src="https://user-images.githubusercontent.com/94840745/227154537-44217a2a-7845-4b00-bdf5-d5bfbe9ef04c.png">

4、带内容区的选项卡，选中样式有误，且缺少分割线
<img width="636" alt="image" src="https://user-images.githubusercontent.com/94840745/227154723-1c948d40-018d-4da0-8db5-c6e9ee89e106.png">

5、带图标的选项卡，图标尺寸有误，偏小了，请参照设计稿
<img width="861" alt="image" src="https://user-images.githubusercontent.com/94840745/227154920-b080c72b-fb08-4ee2-8c49-531eb234a57e.png">

6、胶囊样式中，胶囊高度有误，比设计稿要矮
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/94840745/227155107-6e980a81-6075-4d4e-bd23-c8a3c3b62647.png">

7、demo中元素间的间距过大

**Comment by Luozf12345** [comment]
底部导航条看了是16*3，与设计稿一致。其他问题已修改
